parent_config: tools/SwiftLint/base.yml

excluded:
  - NimbleMediumTests/Sources/Mocks/Sourcery/AutoMockable.generated.swift
  - NimbleMediumTests/Sources/Utilities/R.generated.swift
  - Pods
  - Derived
  - DerivedData
